export interface SymbolEntry {
  char: string;
  name: string;
}

export const SYMBOL_CATEGORIES: Record<string, SymbolEntry[]> = {
  'General Punctuation': [
    { char: '©', name: 'copyright' }, { char: '®', name: 'registered' }, { char: '™', name: 'trademark' },
    { char: '§', name: 'section' }, { char: '¶', name: 'pilcrow paragraph' }, { char: '†', name: 'dagger' },
    { char: '‡', name: 'double dagger' }, { char: '•', name: 'bullet' }, { char: '‣', name: 'triangular bullet' },
    { char: '…', name: 'ellipsis' }, { char: '‰', name: 'per mille' }, { char: '‱', name: 'per ten thousand' },
    { char: '№', name: 'numero' }, { char: '°', name: 'degree' }, { char: '′', name: 'prime' },
    { char: '″', name: 'double prime' }, { char: '‴', name: 'triple prime' }, { char: '‾', name: 'overline' },
    { char: '¦', name: 'broken bar' }, { char: '¬', name: 'not' },
  ],
  Currency: [
    { char: '$', name: 'dollar' }, { char: '€', name: 'euro' }, { char: '£', name: 'pound' },
    { char: '¥', name: 'yen' }, { char: '¢', name: 'cent' }, { char: '₹', name: 'rupee' },
    { char: '₩', name: 'won' }, { char: '₽', name: 'ruble' }, { char: '₺', name: 'lira' },
    { char: '₴', name: 'hryvnia' }, { char: '₫', name: 'dong' }, { char: '฿', name: 'baht' },
    { char: '₦', name: 'naira' }, { char: '₱', name: 'peso' },
  ],
  Mathematical: [
    { char: '±', name: 'plus minus' }, { char: '×', name: 'multiply times' }, { char: '÷', name: 'divide' },
    { char: '≈', name: 'approximately equal' }, { char: '≠', name: 'not equal' }, { char: '≤', name: 'less than or equal' },
    { char: '≥', name: 'greater than or equal' }, { char: '∞', name: 'infinity' }, { char: '√', name: 'square root' },
    { char: '∛', name: 'cube root' }, { char: 'π', name: 'pi' }, { char: '∑', name: 'summation sigma' },
    { char: '∏', name: 'product pi' }, { char: '∆', name: 'delta' }, { char: '∂', name: 'partial differential' },
    { char: '∫', name: 'integral' }, { char: '∮', name: 'contour integral' }, { char: '∇', name: 'nabla gradient' },
    { char: '∈', name: 'element of' }, { char: '∉', name: 'not element of' }, { char: '⊂', name: 'subset' },
    { char: '⊃', name: 'superset' }, { char: '∪', name: 'union' }, { char: '∩', name: 'intersection' },
    { char: '∅', name: 'empty set' }, { char: '∀', name: 'for all' }, { char: '∃', name: 'exists' },
    { char: '¬', name: 'logical not' }, { char: '∧', name: 'logical and' }, { char: '∨', name: 'logical or' },
    { char: '⊕', name: 'circled plus xor' }, { char: '⊗', name: 'circled times' }, { char: '∝', name: 'proportional to' },
    { char: '∴', name: 'therefore' }, { char: '∵', name: 'because' }, { char: '½', name: 'one half' },
    { char: '⅓', name: 'one third' }, { char: '¼', name: 'one quarter' }, { char: '¾', name: 'three quarters' },
  ],
  'Arrows': [
    { char: '←', name: 'left arrow' }, { char: '→', name: 'right arrow' }, { char: '↑', name: 'up arrow' },
    { char: '↓', name: 'down arrow' }, { char: '↔', name: 'left right arrow' }, { char: '↕', name: 'up down arrow' },
    { char: '⇒', name: 'right double arrow implies' }, { char: '⇐', name: 'left double arrow' },
    { char: '⇔', name: 'left right double arrow iff' }, { char: '↩', name: 'return arrow' },
    { char: '↪', name: 'forward arrow hook' }, { char: '⤴', name: 'arrow up right' }, { char: '⤵', name: 'arrow down right' },
    { char: '↖', name: 'up left arrow' }, { char: '↗', name: 'up right arrow' }, { char: '↘', name: 'down right arrow' },
    { char: '↙', name: 'down left arrow' },
  ],
  'Greek Letters': [
    { char: 'α', name: 'alpha' }, { char: 'β', name: 'beta' }, { char: 'γ', name: 'gamma' },
    { char: 'δ', name: 'delta lowercase' }, { char: 'ε', name: 'epsilon' }, { char: 'ζ', name: 'zeta' },
    { char: 'η', name: 'eta' }, { char: 'θ', name: 'theta' }, { char: 'ι', name: 'iota' },
    { char: 'κ', name: 'kappa' }, { char: 'λ', name: 'lambda' }, { char: 'μ', name: 'mu' },
    { char: 'ν', name: 'nu' }, { char: 'ξ', name: 'xi' }, { char: 'ο', name: 'omicron' },
    { char: 'ρ', name: 'rho' }, { char: 'σ', name: 'sigma' }, { char: 'τ', name: 'tau' },
    { char: 'υ', name: 'upsilon' }, { char: 'φ', name: 'phi' }, { char: 'χ', name: 'chi' },
    { char: 'ψ', name: 'psi' }, { char: 'ω', name: 'omega lowercase' },
    { char: 'Α', name: 'Alpha uppercase' }, { char: 'Β', name: 'Beta uppercase' }, { char: 'Γ', name: 'Gamma uppercase' },
    { char: 'Δ', name: 'Delta uppercase' }, { char: 'Θ', name: 'Theta uppercase' }, { char: 'Λ', name: 'Lambda uppercase' },
    { char: 'Ξ', name: 'Xi uppercase' }, { char: 'Π', name: 'Pi uppercase' }, { char: 'Σ', name: 'Sigma uppercase' },
    { char: 'Φ', name: 'Phi uppercase' }, { char: 'Ψ', name: 'Psi uppercase' }, { char: 'Ω', name: 'Omega uppercase' },
  ],
  'Latin Accented': [
    { char: 'à', name: 'a grave' }, { char: 'á', name: 'a acute' }, { char: 'â', name: 'a circumflex' },
    { char: 'ä', name: 'a umlaut diaeresis' }, { char: 'ã', name: 'a tilde' }, { char: 'å', name: 'a ring' },
    { char: 'ç', name: 'c cedilla' }, { char: 'è', name: 'e grave' }, { char: 'é', name: 'e acute' },
    { char: 'ê', name: 'e circumflex' }, { char: 'ë', name: 'e umlaut' }, { char: 'ì', name: 'i grave' },
    { char: 'í', name: 'i acute' }, { char: 'î', name: 'i circumflex' }, { char: 'ï', name: 'i umlaut' },
    { char: 'ñ', name: 'n tilde' }, { char: 'ò', name: 'o grave' }, { char: 'ó', name: 'o acute' },
    { char: 'ô', name: 'o circumflex' }, { char: 'ö', name: 'o umlaut' }, { char: 'õ', name: 'o tilde' },
    { char: 'ù', name: 'u grave' }, { char: 'ú', name: 'u acute' }, { char: 'û', name: 'u circumflex' },
    { char: 'ü', name: 'u umlaut' }, { char: 'ý', name: 'y acute' }, { char: 'ÿ', name: 'y umlaut' },
    { char: 'æ', name: 'ae ligature' }, { char: 'œ', name: 'oe ligature' }, { char: 'ø', name: 'o slash' },
    { char: 'ß', name: 'sharp s eszett' },
  ],
  'Card Suits & Misc': [
    { char: '♠', name: 'spade' }, { char: '♥', name: 'heart' }, { char: '♦', name: 'diamond' },
    { char: '♣', name: 'club' }, { char: '★', name: 'star filled' }, { char: '☆', name: 'star outline' },
    { char: '☺', name: 'smiley face' }, { char: '☹', name: 'frowny face' }, { char: '✓', name: 'checkmark' },
    { char: '✗', name: 'x mark' }, { char: '☑', name: 'checked box' }, { char: '☐', name: 'empty box' },
    { char: '⚠', name: 'warning sign' }, { char: '⚡', name: 'lightning bolt' }, { char: '☀', name: 'sun' },
    { char: '☁', name: 'cloud' }, { char: '☂', name: 'umbrella' },
  ],
};
